[package]
name = "replace_in_file"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
regex = "1.5"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.2"
predicates = "2.1"

[[bin]]
name = "replace_in_file"
path = "src/main.rs"
